### ISSUE TITLE
Missing method for getting books by designations

### ISSUE THREAD

**Issue by sanevillain** [library-angels/code-library-backend#28]
Guys, correct me if I'm wrong, but I couldn't find a route that can supply me with all the books belonging the a specific designation. While having a method for getting all of the books with a limit and an offset is convenient, I'd really appreciate a route that when given a designation id and a limit and an offset can supply me with all of the books belonging to this group. And if no limit and offset are given I'd prefer the default to be all of the available books.

**Comment by alexeybi** [comment]
@sanevillain You're right there's no such method yet, will add it in the upcoming PR.

**Comment by code-mm** [comment]
Issue moved to Jira board.
